# SPDX-FileCopyrightText: 2026 Lin Jian <me@linj.tech>
# SPDX-License-Identifier: GPL-3.0-or-later
name: Check links (local and remote)
on:
  workflow_call:
  schedule:
    - cron: '21 8 * * SAT'
      timezone: "Asia/Shanghai"
# zizmor: ignore[concurrency-limits] because
# - schedule run does not need concurrency
# - workflow_call run is guarded by the caller workflow's concurrency
permissions: {}
jobs:
  check-links:
    name: Check links (local and remote)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31.11.0
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators
      - run: nix run .#check-links -- .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
